services:
  mongodb:
    image: mongo:7.0
    container_name: gorillaz-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: gorillazbot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gorillaz-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gorillaz-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "MTI5OTUyOTk2ODkzMzY3MDk0Mg.Gogurj.pKyF8QUyAZzbcxTbujRXFBspGwTC3CCPQEF5DU"
      MONGODB_CONNECTION_STRING: "mongodb://mongodb:27017"
      MONGODB_DATABASE_NAME: "gorillazbot"
      TZ: "America/Sao_Paulo"
    depends_on:
      - mongodb
    networks:
      - gorillaz-network

volumes:
  mongodb_data:

networks:
  gorillaz-network:
    driver: bridge
