apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: gorillaz
type: Opaque
stringData:
  DISCORD_TOKEN: "MTI5OTUyOTk2ODkzMzY3MDk0Mg.Gogurj.pKyF8QUyAZzbcxTbujRXFBspGwTC3CCPQEF5DU"
  OWM_API_KEY: ""
