apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: gorillaz
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: gorillazbot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bot-config
            - secretRef:
                name: bot-secret
          env:
            - name: MONGODB_CONNECTION_STRING
              value: mongodb://mongodb:27017
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
