apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gorillaz

resources:
  - namespace.yaml
  - mongodb-headless-service.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - bot-configmap.yaml
  - bot-secret.yaml
  - bot-deployment.yaml

images:
  - name: gorillazbot
    newName: gorillazbot
    newTag: latest
