name: CI

on:
  workflow_call:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore GorillazDiscordBot.sln

    - name: Build
      run: dotnet build GorillazDiscordBot.sln -c Release --no-restore

    - name: Test
      run: dotnet test GorillazDiscordBot.sln -c Release --no-build
